### PR TITLE
Prepare for a new feature

### PR DESCRIPTION
**Pull request by benthorner**
This upgrades dependencies and fixes the build in preparation for adding a new feature: busy worker stats. Rather than implement the feature here, this PR is solely about preparation work, which is beneficial in its own right. Some of the changes are based on my limited knowledge of what should be necessary for the build to work - I'm open to suggestions!

### CODE REVIEW

**Comment by phstc** [comment]
Hi @benthorner 

This looks great! I will be happy :shipit: 

Should I go ahead and merge it or are you still working on it?

**Comment by benthorner** [comment]
@phstc thanks for taking a look! I'm all done with this branch, so feel free to merge if you're happy with it - I'm guessing that triggers a gem release?

After this, my plan is to put up another PR to add a few more metrics, using the [workers API](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L916) that was added in v2.7 to expose stats about the jobs currently being worked on.

**Comment by benthorner** [comment]
Update: after writing the last comment I noticed the README was slightly out-of-date. Amended the last commit to fix.

**Comment by phstc** [comment]
@benthorner yay - thanks a ton. I've just released the new version 1.0.0.

**Pull request merged**
